Handle server.basePath in is_kibana_ready check
bitnami/bitnami-docker-kibana pull request #49
Opened 2021-05-21 20:56 UTC by jerryharrow

If server.basePath is configured, it is necessary to use it when querying the API endpoint to check for successful startup.

When polling the /api/status endpoint to determine when kibana has started, include the server.basePath if so configured.
If server.basePath is not configured no change in behavior.

**Benefits**

Enables use of configuration.server.basePath via the bitnami/kibana helm chart to work properly.

**Possible drawbacks**
Add a small lookup of the server.basePath value from the yaml in the startup loop.
I considered refactoring it out, but as it is in a polling loop during startup, that
seemed to be an unnecessary optimization.

**Applicable issues**
Fixed only for the  latest 7.10.2 debian-10 version of the libkibana.sh script.
Same defect exists in other copies of the script for version 6 & 7.

**Additional information**

Verified that without server.basePath present in the kibana.yaml no change in behavior.
Tested with server.basePath present in the kibana.yaml and it now starts successfully when it previously just failed.

2021-05-24 07:51 UTC, juan131 requested changes
Thanks so much for your contribution! We really appreciate it!!

Could you please take a look to my suggestion?

2021-05-24 07:51 UTC, juan131 commented on 7.10.2/debian-10/rootfs/opt/bitnami/scripts/libkibana.sh
> +    local basePath=$(yq r $KIBANA_CONF_FILE "[server.basePath]")
I think we should create a `kibana_conf_get` function (very similar to the `kibana_conf_set` we already have) and use it here:
```suggestion
    local basePath
    basePath="$(kibana_conf_get "server.basePath")"
```

2021-05-24 13:34 UTC, jerryharrow commented
> Thanks so much for your contribution! We really appreciate it!!
> 
> Could you please take a look to my suggestion?

Thanks for the review.
Added kibana_conf_get() method in updated patch.

2021-05-24 13:54 UTC, jerryharrow commented
So it looks like the latest/active code is the 7/debian-10 tree.   I presume I should apply that change to that directory tree as well?

2021-05-24 14:50 UTC, juan131 commented
Correct @jerryharrow ! Both branches should be updated with the same changes. Thanks in advance.

2021-05-24 16:16 UTC, migruiz4 reviewed
Hi @jerryharrow,

I left my suggestion based on our discussion, so both `rewriteBasePath` true/false can be used.

2021-05-24 16:16 UTC, migruiz4 commented on 7/debian-10/rootfs/opt/bitnami/scripts/libkibana.sh
> +        local -r state="$(yq r - "status.overall.state" <<<"$(curl -s "127.0.0.1:${KIBANA_PORT_NUMBER}${basePath}/api/status")")"
Hi @jerryharrow,

As discussed here https://github.com/bitnami/bitnami-docker-kibana/issues/48#issuecomment-847134835, this has to be conditional depending on the value of `server.rewriteBasePath` in the Kibana configuration.

According to Kibana documentation, the default value is `true`, so I'd recommend doing the following:
```suggestion
     local basePath=$(kibana_conf_get "[server.basePath]")
     local rewriteBasePath=$(kibana_conf_get "[server.basePath]")
     if is_kibana_running; then
         if [[ "$rewriteBasePath" == "false" ]]; then
             local -r state="$(yq r - "status.overall.state" <<<"$(curl -s "127.0.0.1:${KIBANA_PORT_NUMBER}/api/status")")"
         else
             local -r state="$(yq r - "status.overall.state" <<<"$(curl -s "127.0.0.1:${KIBANA_PORT_NUMBER}${basePath}/api/status")")"
         fi
```

2021-05-24 18:58 UTC, jerryharrow commented on 7/debian-10/rootfs/opt/bitnami/scripts/libkibana.sh
> +        local -r state="$(yq r - "status.overall.state" <<<"$(curl -s "127.0.0.1:${KIBANA_PORT_NUMBER}${basePath}/api/status")")"
Added check to rewriteBasePath.

2021-05-25 06:37 UTC, juan131 approved these changes

2021-05-25 07:11 UTC, merged

2021-05-25 07:12 UTC, juan131 commented
Your changes were approved/merged.

What's next? A new revision of the Bitnami Kibana container (`7.10.2-debian-10-r107`) will be released within the next hours including your changes.

Thanks again for the contribution!

2021-05-25 12:21 UTC, jerryharrow commented
Closes #49