Display init script output to stdout instead of a file
bitnami/bitnami-docker-kibana pull request #50
Opened 2021-06-03 19:28 UTC by jerryharrow

**Description of the change**

Currently, if kibnana fails to complete startup within the default timeout, it exits with the ERROR:
kibana 19:11:48.06 ERROR ==> Kibana is not available after N retries

but no context as to why that is the case is printed because the log messages from initialization are saved in init_scripts_start.log and never displayed.   This change removes the log file redirection letting the initialization messages go to stdout/stderr so are visible intermixed with other messages.   Once it gets past initialization, other kibana log messages are displayed to stdout.

**Benefits**

Show the logs related to why initialization has not completed.  For example, some plugins such as "savedobjects-service" required elasticsearch to be up and responding to do their work.   If elasticsearch is not ready to do this quickly enough initialization may not complete within the timeout and then  kibana exits and restarts with no way to figure out why that might have been the case.

**Possible drawbacks**

Additional logging messages during the init phase will be displayed.  They could potentially be interwoven with the existing initialization log messages.   

**Applicable issues**

**Additional information**

2021-06-04 09:52 UTC, juan131 reviewed
Hi @jerryharrow 

Thanks so much for the contribution! I'm thinking on a different approach: what about printing the content of the log file if we detect sth is wrong in the "wait_for_kibana_ready" function?

We do sth similar in Jenkins in the `jenkins_wait_for_startup_log_entry`, see: https://github.com/bitnami/bitnami-docker-jenkins/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libjenkins.sh#L79

2021-06-04 12:49 UTC, jerryharrow commented
Hi @juan131 

>  what about printing the content of the log file if we detect sth is wrong in the "wait_for_kibana_ready" function?

I did actually pursue that path  first (earlier commit on my branch https://github.com/bitnami/bitnami-docker-kibana/pull/50/commits/969bb6b5571ad6f3a48ee4b4a4cec1540f7c801d) , but strangely when I build bitnami-docker-kibana/7/debian-10 which I do with just that directory:

docker build .

And then deploy it, then init_scripts_start.log never gets created and the the content just ends up displaying directly in the stdout anyway.    I was reluctant to submit it since I couldn't actually test that path when I build it :-)

Any idea why when I build locally I seem to get different results?  
It does pull in a newer kibana version.   Maybe an error on my part, but I tried it several times.   I can try again.

2021-06-04 13:09 UTC, jerryharrow commented
I just tried it again, and I get the same behavior.    When I build the container the /opt/bitnami/kibana/logs/init_scripts_start.log is not created (despite the CLI argument being present), and the messages instead come to stdout intermixed with the libkibana.sh tracing.   

Here is the container log:
{"type":"log","@timestamp":"2021-06-04T13:05:03+00:00","tags":["info","savedobjects-service"],"pid":70,"message":"Starting saved objects migrations"}
{"type":"log","@timestamp":"2021-06-04T13:05:03+00:00","tags":["info","savedobjects-service"],"pid":70,"message":"[.kibana] INIT -> CREATE_NEW_TARGET. took: 26ms."}
kibana 13:05:03.50 DEBUG ==> Waiting for Kibana server: 2 remaining attempts...
{"type":"log","@timestamp":"2021-06-04T13:05:03+00:00","tags":["info","savedobjects-service"],"pid":70,"message":"[.kibana_task_manager] INIT -> CREATE_NEW_TARGET. took: 117ms."}
kibana 13:05:05.57 DEBUG ==> Waiting for Kibana server: 1 remaining attempts...
kibana 13:05:07.63 ERROR ==> Kibana is not available after 5 retries

If I quickly exec into the container before it restarts:

[dev@harrow-pp OVAD]$ k exec -it ovad-kibana-fdf4d5569-hh4p2 bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I have no name!@ovad-kibana-fdf4d5569-hh4p2:/$
I have no name!@ovad-kibana-fdf4d5569-hh4p2:/$
I have no name!@ovad-kibana-fdf4d5569-hh4p2:/$ ps x
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /bin/bash /opt/bitnami/scripts/kibana/entrypoint.sh /opt/bitnami/scripts/kibana/run.sh
   12 ?        S      0:00 /bin/bash /opt/bitnami/scripts/kibana/setup.sh
   41 ?        S      0:00 /bin/bash /opt/bitnami/scripts/kibana/setup.sh
   42 ?        Sl     0:00 /opt/bitnami/kibana/bin/../node/bin/node /opt/bitnami/kibana/bin/../src/cli/dist serve --host 127.0.0.1 --log-file /opt/bitnami/kibana/logs/init_scripts_start.log
   70 ?        Rl     0:07 /opt/bitnami/kibana/node/bin/node --preserve-symlinks-main --preserve-symlinks /opt/bitnami/kibana/src/cli/dist serve --host 127.0.0.1 --log-file /opt/bitnami/kibana/logs/i
  106 pts/0    Ss     0:00 bash
  136 ?        S      0:00 sleep 2
  138 pts/0    R+     0:00 ps x
I have no name!@ovad-kibana-fdf4d5569-hh4p2:/$ ls -l /opt/bitnami/kibana/logs/init_scripts_start.log
ls: cannot access '/opt/bitnami/kibana/logs/init_scripts_start.log': No such file or directory

I will gladly submit the code with the changes you suggest, but I can't actually test it since the behavior is different.
Sigh.  Any suggestions?

2021-06-07 10:56 UTC, rafariossaa commented
Maybe, to debug it, you can do the following.

- Change the entrypoint in the container image to `tail -f /dev/null`
- Disable or remove the liveness/readines tests.
- Exec into the pod and launch by hand the steps in entrypoint.sh , setup.sh and run.sh following the logic in the scripts.

That way you will be able to start kibana and check is there is any hidden error or other things that should be taken into account.

2021-06-08 09:45 UTC, rafariossaa approved these changes
LGTM
Thanks for adding this feature to the chart.

2021-06-08 09:47 UTC, rafariossaa requested changes

2021-06-08 09:47 UTC, rafariossaa commented on 7/debian-10/rootfs/opt/bitnami/scripts/libkibana.sh
> +        if [[ -r ${KIBANA_LOGS_DIR}/init_scripts_start.log ]]; then
To avoid issues with white spaces in the environment vars used for directories you should enclose this in double quotes.
`if [[ -r ${KIBANA_LOGS_DIR}/init_scripts_start.log ]]`
Should be:
`if [[ -r "${KIBANA_LOGS_DIR}/init_scripts_start.log" ]]`

2021-06-08 09:47 UTC, rafariossaa commented on 7/debian-10/rootfs/opt/bitnami/scripts/libkibana.sh
> +            cat ${KIBANA_LOGS_DIR}/init_scripts_start.log
Same as above.

2021-06-10 07:41 UTC, merged